name: Validate Dockerfile and Docker Compose

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    validate-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v7

            - name: Validate Dockerfile with hadolint
              uses: hadolint/hadolint-action@v3.3.0
              with:
                  context: .
                  dockerfile: Dockerfile

            - name: Validate docker-compose.yaml
              run: docker compose -f docker-compose.yaml config
